name: lodgify
description: Lodgify - Flutter Technical Challenge.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.0
  http: ^0.13.4
  provider: ^6.0.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.17
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: SourceSansProRegular
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    - family: SourceSansProBold
      fonts:
        - asset: assets/fonts/SourceSansPro-Bold.ttf
