// Mocks generated by Mockito 5.0.17 from annotations
// in lodgify/test/viewmodel_tests/home_vm_test/setup/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:lodgify/services/network/dtos/group_dto.dart' as _i5;
import 'package:lodgify/services/network/repos/igroup_network_repo.dart' as _i3;
import 'package:lodgify/services/network/resources/response_network.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponseNetwork_0<DTO> extends _i1.Fake
    implements _i2.ResponseNetwork<DTO> {}

/// A class which mocks [IGroupNetworkRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGroupNetworkRepo extends _i1.Mock implements _i3.IGroupNetworkRepo {
  @override
  _i4.Future<_i2.ResponseNetwork<List<_i5.GroupDto>>> getGroups() =>
      (super.noSuchMethod(Invocation.method(#getGroups, []),
          returnValue: Future<_i2.ResponseNetwork<List<_i5.GroupDto>>>.value(
              _FakeResponseNetwork_0<List<_i5.GroupDto>>())) as _i4
          .Future<_i2.ResponseNetwork<List<_i5.GroupDto>>>);
}
