name: Lodgify CI/CD
on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
jobs:
  BUILD_TEST_RELEASE:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.0'
    - run: flutter config --enable-windows-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --split-per-abi
    - uses: actions/upload-artifact@v1
      with:
        name: lodgify android apk build
        path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
    - run: flutter build windows
    - uses: actions/upload-artifact@v1
      with:
        name: lodgify windows exe build
        path: build/windows/runner/Release